### ISSUE TITLE
Leverage browser caching

### ISSUE THREAD

**Issue by SKBruck** [nsbasic/volt-docs#40]
This rule triggers when PageSpeed Insights detects that the response from your server does not include caching headers or if the resources are specified to be cached for only a short time. https://developers.google.com/speed/docs/insights/LeverageBrowserCaching

Improves mobile and desktop speed

**Comment by SKBruck** [comment]
May be the same as #36

**Comment by artlogic** [comment]
Docs are going away - closing.
